-- Currículo do candidato PCD: ele escolhe entre montar o currículo pela
-- própria plataforma (experiência, formação e habilidades, cada uma numa
-- tabela filha, mesmo padrão das listas de item da vaga) ou simplesmente
-- enviar um PDF já pronto — TIPOCURRICULO diz qual das duas formas vale,
-- igual TIPOCONTEUDO já faz para o curso (LINK ou ARQUIVO).
ALTER TABLE TBLCDSUSR0
  ADD COLUMN TITULOPROFISSIONAL VARCHAR(150) NULL,
  ADD COLUMN TIPOCURRICULO ENUM('PLATAFORMA','PDF') NOT NULL DEFAULT 'PLATAFORMA',
  ADD COLUMN CURRICULOPDF VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS TBLCDSPCDEXP0 (
  IDEXPERIENCIA INT NOT NULL AUTO_INCREMENT,
  IDPCD INT NOT NULL,
  CARGO VARCHAR(150) NOT NULL,
  EMPRESA VARCHAR(150) NOT NULL,
  PERIODO VARCHAR(50) NULL,
  DESCRICAO TEXT NULL,
  PRIMARY KEY (IDEXPERIENCIA),
  CONSTRAINT FK_PCDEXP_PCD FOREIGN KEY (IDPCD) REFERENCES TBLCDSUSR0 (IDPCD) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSPCDFORM0 (
  IDFORMACAO INT NOT NULL AUTO_INCREMENT,
  IDPCD INT NOT NULL,
  CURSO VARCHAR(150) NOT NULL,
  INSTITUICAO VARCHAR(150) NOT NULL,
  PERIODO VARCHAR(50) NULL,
  PRIMARY KEY (IDFORMACAO),
  CONSTRAINT FK_PCDFORM_PCD FOREIGN KEY (IDPCD) REFERENCES TBLCDSUSR0 (IDPCD) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSPCDHAB0 (
  IDHABILIDADE INT NOT NULL AUTO_INCREMENT,
  IDPCD INT NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (IDHABILIDADE),
  CONSTRAINT FK_PCDHAB_PCD FOREIGN KEY (IDPCD) REFERENCES TBLCDSUSR0 (IDPCD) ON DELETE CASCADE
);
