-- Tabela de candidaturas: inscrição de um candidato (PCD) em uma vaga.
-- A tela de acompanhamento de inscritos ainda não existe; por enquanto os
-- registros precisam ser inseridos manualmente até o fluxo de inscrição existir.
CREATE TABLE IF NOT EXISTS TBLCDSCAND0 (
  IDCANDIDATURA INT NOT NULL AUTO_INCREMENT,
  IDVAGA INT NOT NULL,
  IDPCD INT NOT NULL,
  DTCAD DATETIME DEFAULT CURRENT_TIMESTAMP,
  STATUSCANDIDATURA ENUM('PENDENTE','EM_ANALISE','APROVADO','REPROVADO') DEFAULT 'PENDENTE',
  PRIMARY KEY (IDCANDIDATURA),
  CONSTRAINT FK_CANDIDATURA_VAGA FOREIGN KEY (IDVAGA) REFERENCES TBLCDSVAG0 (IDVAGA) ON DELETE CASCADE,
  CONSTRAINT FK_CANDIDATURA_PCD FOREIGN KEY (IDPCD) REFERENCES TBLCDSUSR0 (IDPCD) ON DELETE CASCADE,
  CONSTRAINT UQ_CANDIDATURA UNIQUE (IDVAGA, IDPCD)
);
