-- Cursos passam a ser estruturados em módulos, cada um com suas próprias
-- aulas (capítulos) — cada capítulo tem o próprio conteúdo (link ou vídeo
-- anexado), em vez de um único vídeo/link para o curso inteiro.
-- Com isso, o conteúdo do curso (TIPOCONTEUDO/LINKCURSO/ARQUIVOCURSO) sai da
-- TBLCDSCURSO0 e passa a viver na TBLCDSCURSOCAP0.

CREATE TABLE IF NOT EXISTS TBLCDSCURSOMOD0 (
  IDMODULO INT NOT NULL AUTO_INCREMENT,
  IDCURSO INT NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  PRIMARY KEY (IDMODULO),
  CONSTRAINT FK_CURSOMOD_CURSO FOREIGN KEY (IDCURSO) REFERENCES TBLCDSCURSO0 (IDCURSO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSCURSOCAP0 (
  IDCAPITULO INT NOT NULL AUTO_INCREMENT,
  IDMODULO INT NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  TIPOCONTEUDO ENUM('LINK','ARQUIVO') NOT NULL DEFAULT 'LINK',
  LINKCAPITULO VARCHAR(500) NULL,
  ARQUIVOCAPITULO VARCHAR(255) NULL,
  PRIMARY KEY (IDCAPITULO),
  CONSTRAINT FK_CURSOCAP_MODULO FOREIGN KEY (IDMODULO) REFERENCES TBLCDSCURSOMOD0 (IDMODULO) ON DELETE CASCADE
);

ALTER TABLE TBLCDSCURSO0
  DROP COLUMN TIPOCONTEUDO,
  DROP COLUMN LINKCURSO,
  DROP COLUMN ARQUIVOCURSO;
