-- Migração completa para cursos em módulos/aulas, preservando o conteúdo
-- (link ou vídeo) dos cursos já cadastrados: ele vira a primeira aula de um
-- módulo "Conteúdo" antes das colunas antigas saírem da TBLCDSCURSO0.

USE `conecta+`;

CREATE TABLE IF NOT EXISTS TBLCDSCURSOMOD0 (
  IDMODULO INT NOT NULL AUTO_INCREMENT,
  IDCURSO INT NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  PRIMARY KEY (IDMODULO),
  CONSTRAINT FK_CURSOMOD_CURSO FOREIGN KEY (IDCURSO) REFERENCES TBLCDSCURSO0 (IDCURSO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSCURSOCAP0 (
  IDCAPITULO INT NOT NULL AUTO_INCREMENT,
  IDMODULO INT NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  DESCRICAO TEXT NULL,
  TIPOCONTEUDO ENUM('LINK','ARQUIVO') NOT NULL DEFAULT 'LINK',
  LINKCAPITULO VARCHAR(500) NULL,
  ARQUIVOCAPITULO VARCHAR(255) NULL,
  MATERIAL VARCHAR(255) NULL,
  PRIMARY KEY (IDCAPITULO),
  CONSTRAINT FK_CURSOCAP_MODULO FOREIGN KEY (IDMODULO) REFERENCES TBLCDSCURSOMOD0 (IDMODULO) ON DELETE CASCADE
);

INSERT INTO TBLCDSCURSOMOD0 (IDCURSO, TITULO)
  SELECT IDCURSO, 'Conteúdo'
  FROM TBLCDSCURSO0
  WHERE LINKCURSO IS NOT NULL OR ARQUIVOCURSO IS NOT NULL;

INSERT INTO TBLCDSCURSOCAP0 (IDMODULO, TITULO, TIPOCONTEUDO, LINKCAPITULO, ARQUIVOCAPITULO)
  SELECT m.IDMODULO, c.TITULO, c.TIPOCONTEUDO, c.LINKCURSO, c.ARQUIVOCURSO
  FROM TBLCDSCURSO0 c
  JOIN TBLCDSCURSOMOD0 m ON m.IDCURSO = c.IDCURSO;

ALTER TABLE TBLCDSCURSO0
  DROP COLUMN TIPOCONTEUDO,
  DROP COLUMN LINKCURSO,
  DROP COLUMN ARQUIVOCURSO;
