-- Cidades cadastradas no sistema. Antes, CIDADE/ESTADO eram texto livre
-- direto na TBLCDSVAG0; agora toda vaga aponta pra uma cidade cadastrada
-- aqui (IDCIDADE), pra normalizar o dado.
CREATE TABLE IF NOT EXISTS TBLCDSCID0 (
  IDCIDADE INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  ESTADO CHAR(2) NOT NULL,
  PRIMARY KEY (IDCIDADE),
  CONSTRAINT UQ_CIDADE UNIQUE (NOME, ESTADO)
);

ALTER TABLE TBLCDSVAG0 ADD COLUMN IDCIDADE INT NULL AFTER ESTADO;

-- Migra as cidades já digitadas nas vagas existentes pra TBLCDSCID0, sem duplicar.
INSERT IGNORE INTO TBLCDSCID0 (NOME, ESTADO)
SELECT DISTINCT CIDADE, ESTADO FROM TBLCDSVAG0 WHERE CIDADE IS NOT NULL AND ESTADO IS NOT NULL;

UPDATE TBLCDSVAG0 v
INNER JOIN TBLCDSCID0 c ON c.NOME = v.CIDADE AND c.ESTADO = v.ESTADO
SET v.IDCIDADE = c.IDCIDADE;

ALTER TABLE TBLCDSVAG0
  DROP COLUMN CIDADE,
  DROP COLUMN ESTADO,
  ADD CONSTRAINT FK_VAGA_CIDADE FOREIGN KEY (IDCIDADE) REFERENCES TBLCDSCID0 (IDCIDADE);
