-- Tabela de vagas publicadas pelas empresas.
-- A tela de cadastro de vaga ainda não existe; por enquanto os registros
-- precisam ser inseridos manualmente até o formulário ser criado.
CREATE TABLE IF NOT EXISTS TBLCDSVAG0 (
  IDVAGA INT NOT NULL AUTO_INCREMENT,
  IDEMPRESA INT NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  AREA VARCHAR(100) NULL,
  DESCRICAO TEXT NOT NULL,
  CIDADE VARCHAR(100) NULL,
  ESTADO CHAR(2) NULL,
  MODELOTRABALHO ENUM('PRESENCIAL','HIBRIDO','REMOTO') NOT NULL DEFAULT 'PRESENCIAL',
  TIPOCONTRATACAO ENUM('CLT','PJ','ESTAGIO','TEMPORARIO','FREELANCER') NOT NULL DEFAULT 'CLT',
  SALARIOMIN DECIMAL(10,2) NULL,
  SALARIOMAX DECIMAL(10,2) NULL,
  DTCAD DATETIME DEFAULT CURRENT_TIMESTAMP,
  STATUSVAGA ENUM('ATIVA','INATIVA','ENCERRADA') DEFAULT 'ATIVA',
  PRIMARY KEY (IDVAGA),
  CONSTRAINT FK_VAGA_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES TBLCDSEMP0 (IDEMPRESA) ON DELETE CASCADE
);

-- Listas de itens do cadastro de vaga (uma linha por item), no mesmo padrão
-- das tabelas filhas do candidato (TBLCDSFORM0, TBLCDSHAB0, TBLCDSINT0).
CREATE TABLE IF NOT EXISTS TBLCDSVAGRESP0 (
  IDRESP INT NOT NULL AUTO_INCREMENT,
  IDVAGA INT NOT NULL,
  DESCRICAO VARCHAR(255) NOT NULL,
  PRIMARY KEY (IDRESP),
  CONSTRAINT FK_VAGARESP_VAGA FOREIGN KEY (IDVAGA) REFERENCES TBLCDSVAG0 (IDVAGA) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSVAGREQ0 (
  IDREQ INT NOT NULL AUTO_INCREMENT,
  IDVAGA INT NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  PRIMARY KEY (IDREQ),
  CONSTRAINT FK_VAGAREQ_VAGA FOREIGN KEY (IDVAGA) REFERENCES TBLCDSVAG0 (IDVAGA) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSVAGACS0 (
  IDACS INT NOT NULL AUTO_INCREMENT,
  IDVAGA INT NOT NULL,
  DESCRICAO VARCHAR(255) NOT NULL,
  PRIMARY KEY (IDACS),
  CONSTRAINT FK_VAGAACS_VAGA FOREIGN KEY (IDVAGA) REFERENCES TBLCDSVAG0 (IDVAGA) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TBLCDSVAGBEN0 (
  IDBEN INT NOT NULL AUTO_INCREMENT,
  IDVAGA INT NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  PRIMARY KEY (IDBEN),
  CONSTRAINT FK_VAGABEN_VAGA FOREIGN KEY (IDVAGA) REFERENCES TBLCDSVAG0 (IDVAGA) ON DELETE CASCADE
);
